robot_arm:  
  joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

  robot_arm_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - base_joint
      - waist_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
      - end_eff

    gains:
      base_joint: {p: 10.0, i: 0.001, d: 0.6}
      waist_joint: {p: 10.0, i: 0.001, d: 0.5}
      arm1_joint: {p: 5.0, i: 0.001, d: 0.3}
      arm2_joint: {p: 0.5, i: 0.001, d: 0.04}
      arm3_joint: {p: 0.5, i: 0.001, d: 0.05}
      end_eff: {p: 0.5, i: 0.001, d: 0.05}