controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - waist_joint
      - arm1_joint
      - arm2_joint
      - arm3_joint
initial:  # Define initial robot poses per group
  - group: arm
    pose: Home